# Generated by Django 4.2.1 on 2023-09-06 22:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.DeleteModel(
            name='PostContent',
        ),
    ]
