# Generated by Django 4.2.1 on 2023-09-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_thumbnail_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admin_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
