# Generated by Django 4.2.1 on 2023-10-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_main_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='main_content',
            new_name='is_main_content',
        ),
    ]
