# Generated by Django 4.2.1 on 2023-10-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_main_content_post_is_main_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
