# Generated by Django 4.2.1 on 2023-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_end_date_category_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_biography',
            field=models.BooleanField(default=False),
        ),
    ]
